#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagerApp.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLThuVien")]
	public partial class QLThuVienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttBanDoc(tBanDoc instance);
    partial void UpdatetBanDoc(tBanDoc instance);
    partial void DeletetBanDoc(tBanDoc instance);
    partial void InserttBanSao(tBanSao instance);
    partial void UpdatetBanSao(tBanSao instance);
    partial void DeletetBanSao(tBanSao instance);
    partial void InserttDinhDang(tDinhDang instance);
    partial void UpdatetDinhDang(tDinhDang instance);
    partial void DeletetDinhDang(tDinhDang instance);
    partial void InserttGiaoDich_BanSao(tGiaoDich_BanSao instance);
    partial void UpdatetGiaoDich_BanSao(tGiaoDich_BanSao instance);
    partial void DeletetGiaoDich_BanSao(tGiaoDich_BanSao instance);
    partial void InserttNgonNgu(tNgonNgu instance);
    partial void UpdatetNgonNgu(tNgonNgu instance);
    partial void DeletetNgonNgu(tNgonNgu instance);
    partial void InserttGiaoDichMuonTra(tGiaoDichMuonTra instance);
    partial void UpdatetGiaoDichMuonTra(tGiaoDichMuonTra instance);
    partial void DeletetGiaoDichMuonTra(tGiaoDichMuonTra instance);
    partial void InserttNhaXuatBan(tNhaXuatBan instance);
    partial void UpdatetNhaXuatBan(tNhaXuatBan instance);
    partial void DeletetNhaXuatBan(tNhaXuatBan instance);
    partial void InserttNhanVien(tNhanVien instance);
    partial void UpdatetNhanVien(tNhanVien instance);
    partial void DeletetNhanVien(tNhanVien instance);
    partial void InserttQuocGia(tQuocGia instance);
    partial void UpdatetQuocGia(tQuocGia instance);
    partial void DeletetQuocGia(tQuocGia instance);
    partial void InserttTacGia(tTacGia instance);
    partial void UpdatetTacGia(tTacGia instance);
    partial void DeletetTacGia(tTacGia instance);
    partial void InserttTaiKhoan(tTaiKhoan instance);
    partial void UpdatetTaiKhoan(tTaiKhoan instance);
    partial void DeletetTaiKhoan(tTaiKhoan instance);
    partial void InserttTaiLieu(tTaiLieu instance);
    partial void UpdatetTaiLieu(tTaiLieu instance);
    partial void DeletetTaiLieu(tTaiLieu instance);
    partial void InserttTaiLieu_TacGia(tTaiLieu_TacGia instance);
    partial void UpdatetTaiLieu_TacGia(tTaiLieu_TacGia instance);
    partial void DeletetTaiLieu_TacGia(tTaiLieu_TacGia instance);
    partial void InserttTheBanDoc(tTheBanDoc instance);
    partial void UpdatetTheBanDoc(tTheBanDoc instance);
    partial void DeletetTheBanDoc(tTheBanDoc instance);
    partial void InserttTheLoai(tTheLoai instance);
    partial void UpdatetTheLoai(tTheLoai instance);
    partial void DeletetTheLoai(tTheLoai instance);
    partial void InserttVaiTro(tVaiTro instance);
    partial void UpdatetVaiTro(tVaiTro instance);
    partial void DeletetVaiTro(tVaiTro instance);
    #endregion
		
		public QLThuVienDataContext() : 
				base(global::LibraryManagerApp.Properties.Settings.Default.QLThuVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tBanDoc> tBanDocs
		{
			get
			{
				return this.GetTable<tBanDoc>();
			}
		}
		
		public System.Data.Linq.Table<tBanSao> tBanSaos
		{
			get
			{
				return this.GetTable<tBanSao>();
			}
		}
		
		public System.Data.Linq.Table<tDinhDang> tDinhDangs
		{
			get
			{
				return this.GetTable<tDinhDang>();
			}
		}
		
		public System.Data.Linq.Table<tGiaoDich_BanSao> tGiaoDich_BanSaos
		{
			get
			{
				return this.GetTable<tGiaoDich_BanSao>();
			}
		}
		
		public System.Data.Linq.Table<tNgonNgu> tNgonNgus
		{
			get
			{
				return this.GetTable<tNgonNgu>();
			}
		}
		
		public System.Data.Linq.Table<tGiaoDichMuonTra> tGiaoDichMuonTras
		{
			get
			{
				return this.GetTable<tGiaoDichMuonTra>();
			}
		}
		
		public System.Data.Linq.Table<tNhaXuatBan> tNhaXuatBans
		{
			get
			{
				return this.GetTable<tNhaXuatBan>();
			}
		}
		
		public System.Data.Linq.Table<tNhanVien> tNhanViens
		{
			get
			{
				return this.GetTable<tNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tQuocGia> tQuocGias
		{
			get
			{
				return this.GetTable<tQuocGia>();
			}
		}
		
		public System.Data.Linq.Table<tTacGia> tTacGias
		{
			get
			{
				return this.GetTable<tTacGia>();
			}
		}
		
		public System.Data.Linq.Table<tTaiKhoan> tTaiKhoans
		{
			get
			{
				return this.GetTable<tTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<tTaiLieu> tTaiLieus
		{
			get
			{
				return this.GetTable<tTaiLieu>();
			}
		}
		
		public System.Data.Linq.Table<tTaiLieu_TacGia> tTaiLieu_TacGias
		{
			get
			{
				return this.GetTable<tTaiLieu_TacGia>();
			}
		}
		
		public System.Data.Linq.Table<tTheBanDoc> tTheBanDocs
		{
			get
			{
				return this.GetTable<tTheBanDoc>();
			}
		}
		
		public System.Data.Linq.Table<tTheLoai> tTheLoais
		{
			get
			{
				return this.GetTable<tTheLoai>();
			}
		}
		
		public System.Data.Linq.Table<tVaiTro> tVaiTros
		{
			get
			{
				return this.GetTable<tVaiTro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tBanDoc")]
	public partial class tBanDoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBD;
		
		private string _HoDem;
		
		private string _Ten;
		
		private System.DateTime _NgaySinh;
		
		private char _GioiTinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _Email;
		
		private EntitySet<tTheBanDoc> _tTheBanDocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBDChanging(string value);
    partial void OnMaBDChanged();
    partial void OnHoDemChanging(string value);
    partial void OnHoDemChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(char value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public tBanDoc()
		{
			this._tTheBanDocs = new EntitySet<tTheBanDoc>(new Action<tTheBanDoc>(this.attach_tTheBanDocs), new Action<tTheBanDoc>(this.detach_tTheBanDocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBD", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBD
		{
			get
			{
				return this._MaBD;
			}
			set
			{
				if ((this._MaBD != value))
				{
					this.OnMaBDChanging(value);
					this.SendPropertyChanging();
					this._MaBD = value;
					this.SendPropertyChanged("MaBD");
					this.OnMaBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoDem", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoDem
		{
			get
			{
				return this._HoDem;
			}
			set
			{
				if ((this._HoDem != value))
				{
					this.OnHoDemChanging(value);
					this.SendPropertyChanging();
					this._HoDem = value;
					this.SendPropertyChanged("HoDem");
					this.OnHoDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Char(1) NOT NULL")]
		public char GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tBanDoc_tTheBanDoc", Storage="_tTheBanDocs", ThisKey="MaBD", OtherKey="MaBD")]
		public EntitySet<tTheBanDoc> tTheBanDocs
		{
			get
			{
				return this._tTheBanDocs;
			}
			set
			{
				this._tTheBanDocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tTheBanDocs(tTheBanDoc entity)
		{
			this.SendPropertyChanging();
			entity.tBanDoc = this;
		}
		
		private void detach_tTheBanDocs(tTheBanDoc entity)
		{
			this.SendPropertyChanging();
			entity.tBanDoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tBanSao")]
	public partial class tBanSao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBS;
		
		private string _MaTL;
		
		private string _TrangThai;
		
		private EntitySet<tGiaoDich_BanSao> _tGiaoDich_BanSaos;
		
		private EntityRef<tTaiLieu> _tTaiLieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBSChanging(string value);
    partial void OnMaBSChanged();
    partial void OnMaTLChanging(string value);
    partial void OnMaTLChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tBanSao()
		{
			this._tGiaoDich_BanSaos = new EntitySet<tGiaoDich_BanSao>(new Action<tGiaoDich_BanSao>(this.attach_tGiaoDich_BanSaos), new Action<tGiaoDich_BanSao>(this.detach_tGiaoDich_BanSaos));
			this._tTaiLieu = default(EntityRef<tTaiLieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBS", DbType="Char(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBS
		{
			get
			{
				return this._MaBS;
			}
			set
			{
				if ((this._MaBS != value))
				{
					this.OnMaBSChanging(value);
					this.SendPropertyChanging();
					this._MaBS = value;
					this.SendPropertyChanged("MaBS");
					this.OnMaBSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTL", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaTL
		{
			get
			{
				return this._MaTL;
			}
			set
			{
				if ((this._MaTL != value))
				{
					if (this._tTaiLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTLChanging(value);
					this.SendPropertyChanging();
					this._MaTL = value;
					this.SendPropertyChanged("MaTL");
					this.OnMaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tBanSao_tGiaoDich_BanSao", Storage="_tGiaoDich_BanSaos", ThisKey="MaBS", OtherKey="MaBS")]
		public EntitySet<tGiaoDich_BanSao> tGiaoDich_BanSaos
		{
			get
			{
				return this._tGiaoDich_BanSaos;
			}
			set
			{
				this._tGiaoDich_BanSaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTaiLieu_tBanSao", Storage="_tTaiLieu", ThisKey="MaTL", OtherKey="MaTL", IsForeignKey=true)]
		public tTaiLieu tTaiLieu
		{
			get
			{
				return this._tTaiLieu.Entity;
			}
			set
			{
				tTaiLieu previousValue = this._tTaiLieu.Entity;
				if (((previousValue != value) 
							|| (this._tTaiLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tTaiLieu.Entity = null;
						previousValue.tBanSaos.Remove(this);
					}
					this._tTaiLieu.Entity = value;
					if ((value != null))
					{
						value.tBanSaos.Add(this);
						this._MaTL = value.MaTL;
					}
					else
					{
						this._MaTL = default(string);
					}
					this.SendPropertyChanged("tTaiLieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tGiaoDich_BanSaos(tGiaoDich_BanSao entity)
		{
			this.SendPropertyChanging();
			entity.tBanSao = this;
		}
		
		private void detach_tGiaoDich_BanSaos(tGiaoDich_BanSao entity)
		{
			this.SendPropertyChanging();
			entity.tBanSao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tDinhDang")]
	public partial class tDinhDang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDD;
		
		private string _TenDD;
		
		private EntitySet<tTaiLieu> _tTaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDDChanging(string value);
    partial void OnMaDDChanged();
    partial void OnTenDDChanging(string value);
    partial void OnTenDDChanged();
    #endregion
		
		public tDinhDang()
		{
			this._tTaiLieus = new EntitySet<tTaiLieu>(new Action<tTaiLieu>(this.attach_tTaiLieus), new Action<tTaiLieu>(this.detach_tTaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDD", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDD
		{
			get
			{
				return this._MaDD;
			}
			set
			{
				if ((this._MaDD != value))
				{
					this.OnMaDDChanging(value);
					this.SendPropertyChanging();
					this._MaDD = value;
					this.SendPropertyChanged("MaDD");
					this.OnMaDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDD
		{
			get
			{
				return this._TenDD;
			}
			set
			{
				if ((this._TenDD != value))
				{
					this.OnTenDDChanging(value);
					this.SendPropertyChanging();
					this._TenDD = value;
					this.SendPropertyChanged("TenDD");
					this.OnTenDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tDinhDang_tTaiLieu", Storage="_tTaiLieus", ThisKey="MaDD", OtherKey="MaDD")]
		public EntitySet<tTaiLieu> tTaiLieus
		{
			get
			{
				return this._tTaiLieus;
			}
			set
			{
				this._tTaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tTaiLieus(tTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.tDinhDang = this;
		}
		
		private void detach_tTaiLieus(tTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.tDinhDang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tGiaoDich_BanSao")]
	public partial class tGiaoDich_BanSao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGD;
		
		private string _MaBS;
		
		private bool _TinhTrang;
		
		private EntityRef<tBanSao> _tBanSao;
		
		private EntityRef<tGiaoDichMuonTra> _tGiaoDichMuonTra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGDChanging(string value);
    partial void OnMaGDChanged();
    partial void OnMaBSChanging(string value);
    partial void OnMaBSChanged();
    partial void OnTinhTrangChanging(bool value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public tGiaoDich_BanSao()
		{
			this._tBanSao = default(EntityRef<tBanSao>);
			this._tGiaoDichMuonTra = default(EntityRef<tGiaoDichMuonTra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGD", DbType="Char(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGD
		{
			get
			{
				return this._MaGD;
			}
			set
			{
				if ((this._MaGD != value))
				{
					if (this._tGiaoDichMuonTra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGDChanging(value);
					this.SendPropertyChanging();
					this._MaGD = value;
					this.SendPropertyChanged("MaGD");
					this.OnMaGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBS", DbType="Char(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBS
		{
			get
			{
				return this._MaBS;
			}
			set
			{
				if ((this._MaBS != value))
				{
					if (this._tBanSao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBSChanging(value);
					this.SendPropertyChanging();
					this._MaBS = value;
					this.SendPropertyChanged("MaBS");
					this.OnMaBSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit NOT NULL")]
		public bool TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tBanSao_tGiaoDich_BanSao", Storage="_tBanSao", ThisKey="MaBS", OtherKey="MaBS", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tBanSao tBanSao
		{
			get
			{
				return this._tBanSao.Entity;
			}
			set
			{
				tBanSao previousValue = this._tBanSao.Entity;
				if (((previousValue != value) 
							|| (this._tBanSao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tBanSao.Entity = null;
						previousValue.tGiaoDich_BanSaos.Remove(this);
					}
					this._tBanSao.Entity = value;
					if ((value != null))
					{
						value.tGiaoDich_BanSaos.Add(this);
						this._MaBS = value.MaBS;
					}
					else
					{
						this._MaBS = default(string);
					}
					this.SendPropertyChanged("tBanSao");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tGiaoDichMuonTra_tGiaoDich_BanSao", Storage="_tGiaoDichMuonTra", ThisKey="MaGD", OtherKey="MaGD", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tGiaoDichMuonTra tGiaoDichMuonTra
		{
			get
			{
				return this._tGiaoDichMuonTra.Entity;
			}
			set
			{
				tGiaoDichMuonTra previousValue = this._tGiaoDichMuonTra.Entity;
				if (((previousValue != value) 
							|| (this._tGiaoDichMuonTra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tGiaoDichMuonTra.Entity = null;
						previousValue.tGiaoDich_BanSaos.Remove(this);
					}
					this._tGiaoDichMuonTra.Entity = value;
					if ((value != null))
					{
						value.tGiaoDich_BanSaos.Add(this);
						this._MaGD = value.MaGD;
					}
					else
					{
						this._MaGD = default(string);
					}
					this.SendPropertyChanged("tGiaoDichMuonTra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tNgonNgu")]
	public partial class tNgonNgu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNN;
		
		private string _TenNN;
		
		private EntitySet<tTaiLieu> _tTaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNNChanging(string value);
    partial void OnMaNNChanged();
    partial void OnTenNNChanging(string value);
    partial void OnTenNNChanged();
    #endregion
		
		public tNgonNgu()
		{
			this._tTaiLieus = new EntitySet<tTaiLieu>(new Action<tTaiLieu>(this.attach_tTaiLieus), new Action<tTaiLieu>(this.detach_tTaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNN", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNN
		{
			get
			{
				return this._MaNN;
			}
			set
			{
				if ((this._MaNN != value))
				{
					this.OnMaNNChanging(value);
					this.SendPropertyChanging();
					this._MaNN = value;
					this.SendPropertyChanged("MaNN");
					this.OnMaNNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNN
		{
			get
			{
				return this._TenNN;
			}
			set
			{
				if ((this._TenNN != value))
				{
					this.OnTenNNChanging(value);
					this.SendPropertyChanging();
					this._TenNN = value;
					this.SendPropertyChanged("TenNN");
					this.OnTenNNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tNgonNgu_tTaiLieu", Storage="_tTaiLieus", ThisKey="MaNN", OtherKey="MaNN")]
		public EntitySet<tTaiLieu> tTaiLieus
		{
			get
			{
				return this._tTaiLieus;
			}
			set
			{
				this._tTaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tTaiLieus(tTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.tNgonNgu = this;
		}
		
		private void detach_tTaiLieus(tTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.tNgonNgu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tGiaoDichMuonTra")]
	public partial class tGiaoDichMuonTra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGD;
		
		private string _MaTBD;
		
		private string _MaTK;
		
		private System.DateTime _NgayMuon;
		
		private System.DateTime _NgayHenTra;
		
		private System.Nullable<System.DateTime> _NgayTra;
		
		private string _TrangThai;
		
		private EntitySet<tGiaoDich_BanSao> _tGiaoDich_BanSaos;
		
		private EntityRef<tTaiKhoan> _tTaiKhoan;
		
		private EntityRef<tTheBanDoc> _tTheBanDoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGDChanging(string value);
    partial void OnMaGDChanged();
    partial void OnMaTBDChanging(string value);
    partial void OnMaTBDChanged();
    partial void OnMaTKChanging(string value);
    partial void OnMaTKChanged();
    partial void OnNgayMuonChanging(System.DateTime value);
    partial void OnNgayMuonChanged();
    partial void OnNgayHenTraChanging(System.DateTime value);
    partial void OnNgayHenTraChanged();
    partial void OnNgayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tGiaoDichMuonTra()
		{
			this._tGiaoDich_BanSaos = new EntitySet<tGiaoDich_BanSao>(new Action<tGiaoDich_BanSao>(this.attach_tGiaoDich_BanSaos), new Action<tGiaoDich_BanSao>(this.detach_tGiaoDich_BanSaos));
			this._tTaiKhoan = default(EntityRef<tTaiKhoan>);
			this._tTheBanDoc = default(EntityRef<tTheBanDoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGD", DbType="Char(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGD
		{
			get
			{
				return this._MaGD;
			}
			set
			{
				if ((this._MaGD != value))
				{
					this.OnMaGDChanging(value);
					this.SendPropertyChanging();
					this._MaGD = value;
					this.SendPropertyChanged("MaGD");
					this.OnMaGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTBD", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string MaTBD
		{
			get
			{
				return this._MaTBD;
			}
			set
			{
				if ((this._MaTBD != value))
				{
					if (this._tTheBanDoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTBDChanging(value);
					this.SendPropertyChanging();
					this._MaTBD = value;
					this.SendPropertyChanged("MaTBD");
					this.OnMaTBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					if (this._tTaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="Date NOT NULL")]
		public System.DateTime NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this.OnNgayMuonChanging(value);
					this.SendPropertyChanging();
					this._NgayMuon = value;
					this.SendPropertyChanged("NgayMuon");
					this.OnNgayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHenTra", DbType="Date NOT NULL")]
		public System.DateTime NgayHenTra
		{
			get
			{
				return this._NgayHenTra;
			}
			set
			{
				if ((this._NgayHenTra != value))
				{
					this.OnNgayHenTraChanging(value);
					this.SendPropertyChanging();
					this._NgayHenTra = value;
					this.SendPropertyChanged("NgayHenTra");
					this.OnNgayHenTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tGiaoDichMuonTra_tGiaoDich_BanSao", Storage="_tGiaoDich_BanSaos", ThisKey="MaGD", OtherKey="MaGD")]
		public EntitySet<tGiaoDich_BanSao> tGiaoDich_BanSaos
		{
			get
			{
				return this._tGiaoDich_BanSaos;
			}
			set
			{
				this._tGiaoDich_BanSaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTaiKhoan_tGiaoDichMuonTra", Storage="_tTaiKhoan", ThisKey="MaTK", OtherKey="MaTK", IsForeignKey=true)]
		public tTaiKhoan tTaiKhoan
		{
			get
			{
				return this._tTaiKhoan.Entity;
			}
			set
			{
				tTaiKhoan previousValue = this._tTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._tTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tTaiKhoan.Entity = null;
						previousValue.tGiaoDichMuonTras.Remove(this);
					}
					this._tTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.tGiaoDichMuonTras.Add(this);
						this._MaTK = value.MaTK;
					}
					else
					{
						this._MaTK = default(string);
					}
					this.SendPropertyChanged("tTaiKhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTheBanDoc_tGiaoDichMuonTra", Storage="_tTheBanDoc", ThisKey="MaTBD", OtherKey="MaTBD", IsForeignKey=true)]
		public tTheBanDoc tTheBanDoc
		{
			get
			{
				return this._tTheBanDoc.Entity;
			}
			set
			{
				tTheBanDoc previousValue = this._tTheBanDoc.Entity;
				if (((previousValue != value) 
							|| (this._tTheBanDoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tTheBanDoc.Entity = null;
						previousValue.tGiaoDichMuonTras.Remove(this);
					}
					this._tTheBanDoc.Entity = value;
					if ((value != null))
					{
						value.tGiaoDichMuonTras.Add(this);
						this._MaTBD = value.MaTBD;
					}
					else
					{
						this._MaTBD = default(string);
					}
					this.SendPropertyChanged("tTheBanDoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tGiaoDich_BanSaos(tGiaoDich_BanSao entity)
		{
			this.SendPropertyChanging();
			entity.tGiaoDichMuonTra = this;
		}
		
		private void detach_tGiaoDich_BanSaos(tGiaoDich_BanSao entity)
		{
			this.SendPropertyChanging();
			entity.tGiaoDichMuonTra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tNhaXuatBan")]
	public partial class tNhaXuatBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNXB;
		
		private string _MaQG;
		
		private string _TenNXB;
		
		private EntitySet<tTaiLieu> _tTaiLieus;
		
		private EntityRef<tQuocGia> _tQuocGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNXBChanging(string value);
    partial void OnMaNXBChanged();
    partial void OnMaQGChanging(string value);
    partial void OnMaQGChanged();
    partial void OnTenNXBChanging(string value);
    partial void OnTenNXBChanged();
    #endregion
		
		public tNhaXuatBan()
		{
			this._tTaiLieus = new EntitySet<tTaiLieu>(new Action<tTaiLieu>(this.attach_tTaiLieus), new Action<tTaiLieu>(this.detach_tTaiLieus));
			this._tQuocGia = default(EntityRef<tQuocGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNXB", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNXB
		{
			get
			{
				return this._MaNXB;
			}
			set
			{
				if ((this._MaNXB != value))
				{
					this.OnMaNXBChanging(value);
					this.SendPropertyChanging();
					this._MaNXB = value;
					this.SendPropertyChanged("MaNXB");
					this.OnMaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQG", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MaQG
		{
			get
			{
				return this._MaQG;
			}
			set
			{
				if ((this._MaQG != value))
				{
					if (this._tQuocGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQGChanging(value);
					this.SendPropertyChanging();
					this._MaQG = value;
					this.SendPropertyChanged("MaQG");
					this.OnMaQGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNXB", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenNXB
		{
			get
			{
				return this._TenNXB;
			}
			set
			{
				if ((this._TenNXB != value))
				{
					this.OnTenNXBChanging(value);
					this.SendPropertyChanging();
					this._TenNXB = value;
					this.SendPropertyChanged("TenNXB");
					this.OnTenNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tNhaXuatBan_tTaiLieu", Storage="_tTaiLieus", ThisKey="MaNXB", OtherKey="MaNXB")]
		public EntitySet<tTaiLieu> tTaiLieus
		{
			get
			{
				return this._tTaiLieus;
			}
			set
			{
				this._tTaiLieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tQuocGia_tNhaXuatBan", Storage="_tQuocGia", ThisKey="MaQG", OtherKey="MaQG", IsForeignKey=true)]
		public tQuocGia tQuocGia
		{
			get
			{
				return this._tQuocGia.Entity;
			}
			set
			{
				tQuocGia previousValue = this._tQuocGia.Entity;
				if (((previousValue != value) 
							|| (this._tQuocGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tQuocGia.Entity = null;
						previousValue.tNhaXuatBans.Remove(this);
					}
					this._tQuocGia.Entity = value;
					if ((value != null))
					{
						value.tNhaXuatBans.Add(this);
						this._MaQG = value.MaQG;
					}
					else
					{
						this._MaQG = default(string);
					}
					this.SendPropertyChanged("tQuocGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tTaiLieus(tTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.tNhaXuatBan = this;
		}
		
		private void detach_tTaiLieus(tTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.tNhaXuatBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tNhanVien")]
	public partial class tNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _HoDem;
		
		private string _Ten;
		
		private System.DateTime _NgaySinh;
		
		private char _GioiTinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _Email;
		
		private string _PhuTrach;
		
		private EntitySet<tTaiKhoan> _tTaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHoDemChanging(string value);
    partial void OnHoDemChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(char value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhuTrachChanging(string value);
    partial void OnPhuTrachChanged();
    #endregion
		
		public tNhanVien()
		{
			this._tTaiKhoans = new EntitySet<tTaiKhoan>(new Action<tTaiKhoan>(this.attach_tTaiKhoans), new Action<tTaiKhoan>(this.detach_tTaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoDem", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoDem
		{
			get
			{
				return this._HoDem;
			}
			set
			{
				if ((this._HoDem != value))
				{
					this.OnHoDemChanging(value);
					this.SendPropertyChanging();
					this._HoDem = value;
					this.SendPropertyChanged("HoDem");
					this.OnHoDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Char(1) NOT NULL")]
		public char GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuTrach", DbType="NVarChar(100)")]
		public string PhuTrach
		{
			get
			{
				return this._PhuTrach;
			}
			set
			{
				if ((this._PhuTrach != value))
				{
					this.OnPhuTrachChanging(value);
					this.SendPropertyChanging();
					this._PhuTrach = value;
					this.SendPropertyChanged("PhuTrach");
					this.OnPhuTrachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tNhanVien_tTaiKhoan", Storage="_tTaiKhoans", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<tTaiKhoan> tTaiKhoans
		{
			get
			{
				return this._tTaiKhoans;
			}
			set
			{
				this._tTaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tTaiKhoans(tTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tNhanVien = this;
		}
		
		private void detach_tTaiKhoans(tTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tQuocGia")]
	public partial class tQuocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaQG;
		
		private string _TenQG;
		
		private EntitySet<tNhaXuatBan> _tNhaXuatBans;
		
		private EntitySet<tTacGia> _tTacGias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQGChanging(string value);
    partial void OnMaQGChanged();
    partial void OnTenQGChanging(string value);
    partial void OnTenQGChanged();
    #endregion
		
		public tQuocGia()
		{
			this._tNhaXuatBans = new EntitySet<tNhaXuatBan>(new Action<tNhaXuatBan>(this.attach_tNhaXuatBans), new Action<tNhaXuatBan>(this.detach_tNhaXuatBans));
			this._tTacGias = new EntitySet<tTacGia>(new Action<tTacGia>(this.attach_tTacGias), new Action<tTacGia>(this.detach_tTacGias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQG", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaQG
		{
			get
			{
				return this._MaQG;
			}
			set
			{
				if ((this._MaQG != value))
				{
					this.OnMaQGChanging(value);
					this.SendPropertyChanging();
					this._MaQG = value;
					this.SendPropertyChanged("MaQG");
					this.OnMaQGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQG", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenQG
		{
			get
			{
				return this._TenQG;
			}
			set
			{
				if ((this._TenQG != value))
				{
					this.OnTenQGChanging(value);
					this.SendPropertyChanging();
					this._TenQG = value;
					this.SendPropertyChanged("TenQG");
					this.OnTenQGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tQuocGia_tNhaXuatBan", Storage="_tNhaXuatBans", ThisKey="MaQG", OtherKey="MaQG")]
		public EntitySet<tNhaXuatBan> tNhaXuatBans
		{
			get
			{
				return this._tNhaXuatBans;
			}
			set
			{
				this._tNhaXuatBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tQuocGia_tTacGia", Storage="_tTacGias", ThisKey="MaQG", OtherKey="MaQG")]
		public EntitySet<tTacGia> tTacGias
		{
			get
			{
				return this._tTacGias;
			}
			set
			{
				this._tTacGias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tNhaXuatBans(tNhaXuatBan entity)
		{
			this.SendPropertyChanging();
			entity.tQuocGia = this;
		}
		
		private void detach_tNhaXuatBans(tNhaXuatBan entity)
		{
			this.SendPropertyChanging();
			entity.tQuocGia = null;
		}
		
		private void attach_tTacGias(tTacGia entity)
		{
			this.SendPropertyChanging();
			entity.tQuocGia = this;
		}
		
		private void detach_tTacGias(tTacGia entity)
		{
			this.SendPropertyChanging();
			entity.tQuocGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tTacGia")]
	public partial class tTacGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTG;
		
		private string _MaQG;
		
		private string _HoDem;
		
		private string _Ten;
		
		private EntitySet<tTaiLieu_TacGia> _tTaiLieu_TacGias;
		
		private EntityRef<tQuocGia> _tQuocGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTGChanging(string value);
    partial void OnMaTGChanged();
    partial void OnMaQGChanging(string value);
    partial void OnMaQGChanged();
    partial void OnHoDemChanging(string value);
    partial void OnHoDemChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    #endregion
		
		public tTacGia()
		{
			this._tTaiLieu_TacGias = new EntitySet<tTaiLieu_TacGia>(new Action<tTaiLieu_TacGia>(this.attach_tTaiLieu_TacGias), new Action<tTaiLieu_TacGia>(this.detach_tTaiLieu_TacGias));
			this._tQuocGia = default(EntityRef<tQuocGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this.OnMaTGChanging(value);
					this.SendPropertyChanging();
					this._MaTG = value;
					this.SendPropertyChanged("MaTG");
					this.OnMaTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQG", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MaQG
		{
			get
			{
				return this._MaQG;
			}
			set
			{
				if ((this._MaQG != value))
				{
					if (this._tQuocGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQGChanging(value);
					this.SendPropertyChanging();
					this._MaQG = value;
					this.SendPropertyChanged("MaQG");
					this.OnMaQGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoDem", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoDem
		{
			get
			{
				return this._HoDem;
			}
			set
			{
				if ((this._HoDem != value))
				{
					this.OnHoDemChanging(value);
					this.SendPropertyChanging();
					this._HoDem = value;
					this.SendPropertyChanged("HoDem");
					this.OnHoDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTacGia_tTaiLieu_TacGia", Storage="_tTaiLieu_TacGias", ThisKey="MaTG", OtherKey="MaTG")]
		public EntitySet<tTaiLieu_TacGia> tTaiLieu_TacGias
		{
			get
			{
				return this._tTaiLieu_TacGias;
			}
			set
			{
				this._tTaiLieu_TacGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tQuocGia_tTacGia", Storage="_tQuocGia", ThisKey="MaQG", OtherKey="MaQG", IsForeignKey=true)]
		public tQuocGia tQuocGia
		{
			get
			{
				return this._tQuocGia.Entity;
			}
			set
			{
				tQuocGia previousValue = this._tQuocGia.Entity;
				if (((previousValue != value) 
							|| (this._tQuocGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tQuocGia.Entity = null;
						previousValue.tTacGias.Remove(this);
					}
					this._tQuocGia.Entity = value;
					if ((value != null))
					{
						value.tTacGias.Add(this);
						this._MaQG = value.MaQG;
					}
					else
					{
						this._MaQG = default(string);
					}
					this.SendPropertyChanged("tQuocGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tTaiLieu_TacGias(tTaiLieu_TacGia entity)
		{
			this.SendPropertyChanging();
			entity.tTacGia = this;
		}
		
		private void detach_tTaiLieu_TacGias(tTaiLieu_TacGia entity)
		{
			this.SendPropertyChanging();
			entity.tTacGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tTaiKhoan")]
	public partial class tTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTK;
		
		private string _MaNV;
		
		private string _MaVT;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _TrangThai;
		
		private System.DateTime _NgayTao;
		
		private EntitySet<tGiaoDichMuonTra> _tGiaoDichMuonTras;
		
		private EntitySet<tTaiLieu> _tTaiLieus;
		
		private EntitySet<tTheBanDoc> _tTheBanDocs;
		
		private EntityRef<tNhanVien> _tNhanVien;
		
		private EntityRef<tVaiTro> _tVaiTro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTKChanging(string value);
    partial void OnMaTKChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMaVTChanging(string value);
    partial void OnMaVTChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public tTaiKhoan()
		{
			this._tGiaoDichMuonTras = new EntitySet<tGiaoDichMuonTra>(new Action<tGiaoDichMuonTra>(this.attach_tGiaoDichMuonTras), new Action<tGiaoDichMuonTra>(this.detach_tGiaoDichMuonTras));
			this._tTaiLieus = new EntitySet<tTaiLieu>(new Action<tTaiLieu>(this.attach_tTaiLieus), new Action<tTaiLieu>(this.detach_tTaiLieus));
			this._tTheBanDocs = new EntitySet<tTheBanDoc>(new Action<tTheBanDoc>(this.attach_tTheBanDocs), new Action<tTheBanDoc>(this.detach_tTheBanDocs));
			this._tNhanVien = default(EntityRef<tNhanVien>);
			this._tVaiTro = default(EntityRef<tVaiTro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVT", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string MaVT
		{
			get
			{
				return this._MaVT;
			}
			set
			{
				if ((this._MaVT != value))
				{
					if (this._tVaiTro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVTChanging(value);
					this.SendPropertyChanging();
					this._MaVT = value;
					this.SendPropertyChanged("MaVT");
					this.OnMaVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTaiKhoan_tGiaoDichMuonTra", Storage="_tGiaoDichMuonTras", ThisKey="MaTK", OtherKey="MaTK")]
		public EntitySet<tGiaoDichMuonTra> tGiaoDichMuonTras
		{
			get
			{
				return this._tGiaoDichMuonTras;
			}
			set
			{
				this._tGiaoDichMuonTras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTaiKhoan_tTaiLieu", Storage="_tTaiLieus", ThisKey="MaTK", OtherKey="MaTK")]
		public EntitySet<tTaiLieu> tTaiLieus
		{
			get
			{
				return this._tTaiLieus;
			}
			set
			{
				this._tTaiLieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTaiKhoan_tTheBanDoc", Storage="_tTheBanDocs", ThisKey="MaTK", OtherKey="MaTK")]
		public EntitySet<tTheBanDoc> tTheBanDocs
		{
			get
			{
				return this._tTheBanDocs;
			}
			set
			{
				this._tTheBanDocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tNhanVien_tTaiKhoan", Storage="_tNhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tNhanVien tNhanVien
		{
			get
			{
				return this._tNhanVien.Entity;
			}
			set
			{
				tNhanVien previousValue = this._tNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tNhanVien.Entity = null;
						previousValue.tTaiKhoans.Remove(this);
					}
					this._tNhanVien.Entity = value;
					if ((value != null))
					{
						value.tTaiKhoans.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("tNhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tVaiTro_tTaiKhoan", Storage="_tVaiTro", ThisKey="MaVT", OtherKey="MaVT", IsForeignKey=true)]
		public tVaiTro tVaiTro
		{
			get
			{
				return this._tVaiTro.Entity;
			}
			set
			{
				tVaiTro previousValue = this._tVaiTro.Entity;
				if (((previousValue != value) 
							|| (this._tVaiTro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tVaiTro.Entity = null;
						previousValue.tTaiKhoans.Remove(this);
					}
					this._tVaiTro.Entity = value;
					if ((value != null))
					{
						value.tTaiKhoans.Add(this);
						this._MaVT = value.MaVT;
					}
					else
					{
						this._MaVT = default(string);
					}
					this.SendPropertyChanged("tVaiTro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tGiaoDichMuonTras(tGiaoDichMuonTra entity)
		{
			this.SendPropertyChanging();
			entity.tTaiKhoan = this;
		}
		
		private void detach_tGiaoDichMuonTras(tGiaoDichMuonTra entity)
		{
			this.SendPropertyChanging();
			entity.tTaiKhoan = null;
		}
		
		private void attach_tTaiLieus(tTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.tTaiKhoan = this;
		}
		
		private void detach_tTaiLieus(tTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.tTaiKhoan = null;
		}
		
		private void attach_tTheBanDocs(tTheBanDoc entity)
		{
			this.SendPropertyChanging();
			entity.tTaiKhoan = this;
		}
		
		private void detach_tTheBanDocs(tTheBanDoc entity)
		{
			this.SendPropertyChanging();
			entity.tTaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tTaiLieu")]
	public partial class tTaiLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTL;
		
		private string _MaNXB;
		
		private string _MaNN;
		
		private string _MaThL;
		
		private string _MaDD;
		
		private string _MaTK;
		
		private string _TenTL;
		
		private System.Nullable<int> _LanXuatBan;
		
		private System.Nullable<int> _NamXuatBan;
		
		private System.Nullable<int> _SoTrang;
		
		private string _KhoCo;
		
		private string _Anh;
		
		private EntitySet<tBanSao> _tBanSaos;
		
		private EntitySet<tTaiLieu_TacGia> _tTaiLieu_TacGias;
		
		private EntityRef<tDinhDang> _tDinhDang;
		
		private EntityRef<tNgonNgu> _tNgonNgu;
		
		private EntityRef<tNhaXuatBan> _tNhaXuatBan;
		
		private EntityRef<tTaiKhoan> _tTaiKhoan;
		
		private EntityRef<tTheLoai> _tTheLoai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTLChanging(string value);
    partial void OnMaTLChanged();
    partial void OnMaNXBChanging(string value);
    partial void OnMaNXBChanged();
    partial void OnMaNNChanging(string value);
    partial void OnMaNNChanged();
    partial void OnMaThLChanging(string value);
    partial void OnMaThLChanged();
    partial void OnMaDDChanging(string value);
    partial void OnMaDDChanged();
    partial void OnMaTKChanging(string value);
    partial void OnMaTKChanged();
    partial void OnTenTLChanging(string value);
    partial void OnTenTLChanged();
    partial void OnLanXuatBanChanging(System.Nullable<int> value);
    partial void OnLanXuatBanChanged();
    partial void OnNamXuatBanChanging(System.Nullable<int> value);
    partial void OnNamXuatBanChanged();
    partial void OnSoTrangChanging(System.Nullable<int> value);
    partial void OnSoTrangChanged();
    partial void OnKhoCoChanging(string value);
    partial void OnKhoCoChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    #endregion
		
		public tTaiLieu()
		{
			this._tBanSaos = new EntitySet<tBanSao>(new Action<tBanSao>(this.attach_tBanSaos), new Action<tBanSao>(this.detach_tBanSaos));
			this._tTaiLieu_TacGias = new EntitySet<tTaiLieu_TacGia>(new Action<tTaiLieu_TacGia>(this.attach_tTaiLieu_TacGias), new Action<tTaiLieu_TacGia>(this.detach_tTaiLieu_TacGias));
			this._tDinhDang = default(EntityRef<tDinhDang>);
			this._tNgonNgu = default(EntityRef<tNgonNgu>);
			this._tNhaXuatBan = default(EntityRef<tNhaXuatBan>);
			this._tTaiKhoan = default(EntityRef<tTaiKhoan>);
			this._tTheLoai = default(EntityRef<tTheLoai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTL", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTL
		{
			get
			{
				return this._MaTL;
			}
			set
			{
				if ((this._MaTL != value))
				{
					this.OnMaTLChanging(value);
					this.SendPropertyChanging();
					this._MaTL = value;
					this.SendPropertyChanged("MaTL");
					this.OnMaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNXB", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string MaNXB
		{
			get
			{
				return this._MaNXB;
			}
			set
			{
				if ((this._MaNXB != value))
				{
					if (this._tNhaXuatBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNXBChanging(value);
					this.SendPropertyChanging();
					this._MaNXB = value;
					this.SendPropertyChanged("MaNXB");
					this.OnMaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNN", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MaNN
		{
			get
			{
				return this._MaNN;
			}
			set
			{
				if ((this._MaNN != value))
				{
					if (this._tNgonNgu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNNChanging(value);
					this.SendPropertyChanging();
					this._MaNN = value;
					this.SendPropertyChanged("MaNN");
					this.OnMaNNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThL", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string MaThL
		{
			get
			{
				return this._MaThL;
			}
			set
			{
				if ((this._MaThL != value))
				{
					if (this._tTheLoai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThLChanging(value);
					this.SendPropertyChanging();
					this._MaThL = value;
					this.SendPropertyChanged("MaThL");
					this.OnMaThLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDD", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaDD
		{
			get
			{
				return this._MaDD;
			}
			set
			{
				if ((this._MaDD != value))
				{
					if (this._tDinhDang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDDChanging(value);
					this.SendPropertyChanging();
					this._MaDD = value;
					this.SendPropertyChanged("MaDD");
					this.OnMaDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="Char(7)")]
		public string MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					if (this._tTaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTL", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenTL
		{
			get
			{
				return this._TenTL;
			}
			set
			{
				if ((this._TenTL != value))
				{
					this.OnTenTLChanging(value);
					this.SendPropertyChanging();
					this._TenTL = value;
					this.SendPropertyChanged("TenTL");
					this.OnTenTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanXuatBan", DbType="Int")]
		public System.Nullable<int> LanXuatBan
		{
			get
			{
				return this._LanXuatBan;
			}
			set
			{
				if ((this._LanXuatBan != value))
				{
					this.OnLanXuatBanChanging(value);
					this.SendPropertyChanging();
					this._LanXuatBan = value;
					this.SendPropertyChanged("LanXuatBan");
					this.OnLanXuatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamXuatBan", DbType="Int")]
		public System.Nullable<int> NamXuatBan
		{
			get
			{
				return this._NamXuatBan;
			}
			set
			{
				if ((this._NamXuatBan != value))
				{
					this.OnNamXuatBanChanging(value);
					this.SendPropertyChanging();
					this._NamXuatBan = value;
					this.SendPropertyChanged("NamXuatBan");
					this.OnNamXuatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTrang", DbType="Int")]
		public System.Nullable<int> SoTrang
		{
			get
			{
				return this._SoTrang;
			}
			set
			{
				if ((this._SoTrang != value))
				{
					this.OnSoTrangChanging(value);
					this.SendPropertyChanging();
					this._SoTrang = value;
					this.SendPropertyChanged("SoTrang");
					this.OnSoTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoCo", DbType="Char(10)")]
		public string KhoCo
		{
			get
			{
				return this._KhoCo;
			}
			set
			{
				if ((this._KhoCo != value))
				{
					this.OnKhoCoChanging(value);
					this.SendPropertyChanging();
					this._KhoCo = value;
					this.SendPropertyChanged("KhoCo");
					this.OnKhoCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="NVarChar(255)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTaiLieu_tBanSao", Storage="_tBanSaos", ThisKey="MaTL", OtherKey="MaTL")]
		public EntitySet<tBanSao> tBanSaos
		{
			get
			{
				return this._tBanSaos;
			}
			set
			{
				this._tBanSaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTaiLieu_tTaiLieu_TacGia", Storage="_tTaiLieu_TacGias", ThisKey="MaTL", OtherKey="MaTL")]
		public EntitySet<tTaiLieu_TacGia> tTaiLieu_TacGias
		{
			get
			{
				return this._tTaiLieu_TacGias;
			}
			set
			{
				this._tTaiLieu_TacGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tDinhDang_tTaiLieu", Storage="_tDinhDang", ThisKey="MaDD", OtherKey="MaDD", IsForeignKey=true)]
		public tDinhDang tDinhDang
		{
			get
			{
				return this._tDinhDang.Entity;
			}
			set
			{
				tDinhDang previousValue = this._tDinhDang.Entity;
				if (((previousValue != value) 
							|| (this._tDinhDang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tDinhDang.Entity = null;
						previousValue.tTaiLieus.Remove(this);
					}
					this._tDinhDang.Entity = value;
					if ((value != null))
					{
						value.tTaiLieus.Add(this);
						this._MaDD = value.MaDD;
					}
					else
					{
						this._MaDD = default(string);
					}
					this.SendPropertyChanged("tDinhDang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tNgonNgu_tTaiLieu", Storage="_tNgonNgu", ThisKey="MaNN", OtherKey="MaNN", IsForeignKey=true)]
		public tNgonNgu tNgonNgu
		{
			get
			{
				return this._tNgonNgu.Entity;
			}
			set
			{
				tNgonNgu previousValue = this._tNgonNgu.Entity;
				if (((previousValue != value) 
							|| (this._tNgonNgu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tNgonNgu.Entity = null;
						previousValue.tTaiLieus.Remove(this);
					}
					this._tNgonNgu.Entity = value;
					if ((value != null))
					{
						value.tTaiLieus.Add(this);
						this._MaNN = value.MaNN;
					}
					else
					{
						this._MaNN = default(string);
					}
					this.SendPropertyChanged("tNgonNgu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tNhaXuatBan_tTaiLieu", Storage="_tNhaXuatBan", ThisKey="MaNXB", OtherKey="MaNXB", IsForeignKey=true)]
		public tNhaXuatBan tNhaXuatBan
		{
			get
			{
				return this._tNhaXuatBan.Entity;
			}
			set
			{
				tNhaXuatBan previousValue = this._tNhaXuatBan.Entity;
				if (((previousValue != value) 
							|| (this._tNhaXuatBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tNhaXuatBan.Entity = null;
						previousValue.tTaiLieus.Remove(this);
					}
					this._tNhaXuatBan.Entity = value;
					if ((value != null))
					{
						value.tTaiLieus.Add(this);
						this._MaNXB = value.MaNXB;
					}
					else
					{
						this._MaNXB = default(string);
					}
					this.SendPropertyChanged("tNhaXuatBan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTaiKhoan_tTaiLieu", Storage="_tTaiKhoan", ThisKey="MaTK", OtherKey="MaTK", IsForeignKey=true)]
		public tTaiKhoan tTaiKhoan
		{
			get
			{
				return this._tTaiKhoan.Entity;
			}
			set
			{
				tTaiKhoan previousValue = this._tTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._tTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tTaiKhoan.Entity = null;
						previousValue.tTaiLieus.Remove(this);
					}
					this._tTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.tTaiLieus.Add(this);
						this._MaTK = value.MaTK;
					}
					else
					{
						this._MaTK = default(string);
					}
					this.SendPropertyChanged("tTaiKhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTheLoai_tTaiLieu", Storage="_tTheLoai", ThisKey="MaThL", OtherKey="MaThL", IsForeignKey=true)]
		public tTheLoai tTheLoai
		{
			get
			{
				return this._tTheLoai.Entity;
			}
			set
			{
				tTheLoai previousValue = this._tTheLoai.Entity;
				if (((previousValue != value) 
							|| (this._tTheLoai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tTheLoai.Entity = null;
						previousValue.tTaiLieus.Remove(this);
					}
					this._tTheLoai.Entity = value;
					if ((value != null))
					{
						value.tTaiLieus.Add(this);
						this._MaThL = value.MaThL;
					}
					else
					{
						this._MaThL = default(string);
					}
					this.SendPropertyChanged("tTheLoai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tBanSaos(tBanSao entity)
		{
			this.SendPropertyChanging();
			entity.tTaiLieu = this;
		}
		
		private void detach_tBanSaos(tBanSao entity)
		{
			this.SendPropertyChanging();
			entity.tTaiLieu = null;
		}
		
		private void attach_tTaiLieu_TacGias(tTaiLieu_TacGia entity)
		{
			this.SendPropertyChanging();
			entity.tTaiLieu = this;
		}
		
		private void detach_tTaiLieu_TacGias(tTaiLieu_TacGia entity)
		{
			this.SendPropertyChanging();
			entity.tTaiLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tTaiLieu_TacGia")]
	public partial class tTaiLieu_TacGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTL;
		
		private string _MaTG;
		
		private string _VaiTro;
		
		private EntityRef<tTacGia> _tTacGia;
		
		private EntityRef<tTaiLieu> _tTaiLieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTLChanging(string value);
    partial void OnMaTLChanged();
    partial void OnMaTGChanging(string value);
    partial void OnMaTGChanged();
    partial void OnVaiTroChanging(string value);
    partial void OnVaiTroChanged();
    #endregion
		
		public tTaiLieu_TacGia()
		{
			this._tTacGia = default(EntityRef<tTacGia>);
			this._tTaiLieu = default(EntityRef<tTaiLieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTL", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTL
		{
			get
			{
				return this._MaTL;
			}
			set
			{
				if ((this._MaTL != value))
				{
					if (this._tTaiLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTLChanging(value);
					this.SendPropertyChanging();
					this._MaTL = value;
					this.SendPropertyChanged("MaTL");
					this.OnMaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					if (this._tTacGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTGChanging(value);
					this.SendPropertyChanging();
					this._MaTG = value;
					this.SendPropertyChanged("MaTG");
					this.OnMaTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaiTro", DbType="NVarChar(50)")]
		public string VaiTro
		{
			get
			{
				return this._VaiTro;
			}
			set
			{
				if ((this._VaiTro != value))
				{
					this.OnVaiTroChanging(value);
					this.SendPropertyChanging();
					this._VaiTro = value;
					this.SendPropertyChanged("VaiTro");
					this.OnVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTacGia_tTaiLieu_TacGia", Storage="_tTacGia", ThisKey="MaTG", OtherKey="MaTG", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tTacGia tTacGia
		{
			get
			{
				return this._tTacGia.Entity;
			}
			set
			{
				tTacGia previousValue = this._tTacGia.Entity;
				if (((previousValue != value) 
							|| (this._tTacGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tTacGia.Entity = null;
						previousValue.tTaiLieu_TacGias.Remove(this);
					}
					this._tTacGia.Entity = value;
					if ((value != null))
					{
						value.tTaiLieu_TacGias.Add(this);
						this._MaTG = value.MaTG;
					}
					else
					{
						this._MaTG = default(string);
					}
					this.SendPropertyChanged("tTacGia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTaiLieu_tTaiLieu_TacGia", Storage="_tTaiLieu", ThisKey="MaTL", OtherKey="MaTL", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tTaiLieu tTaiLieu
		{
			get
			{
				return this._tTaiLieu.Entity;
			}
			set
			{
				tTaiLieu previousValue = this._tTaiLieu.Entity;
				if (((previousValue != value) 
							|| (this._tTaiLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tTaiLieu.Entity = null;
						previousValue.tTaiLieu_TacGias.Remove(this);
					}
					this._tTaiLieu.Entity = value;
					if ((value != null))
					{
						value.tTaiLieu_TacGias.Add(this);
						this._MaTL = value.MaTL;
					}
					else
					{
						this._MaTL = default(string);
					}
					this.SendPropertyChanged("tTaiLieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tTheBanDoc")]
	public partial class tTheBanDoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTBD;
		
		private string _MaBD;
		
		private string _MaTK;
		
		private System.DateTime _NgayCap;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private string _TrangThai;
		
		private EntitySet<tGiaoDichMuonTra> _tGiaoDichMuonTras;
		
		private EntityRef<tBanDoc> _tBanDoc;
		
		private EntityRef<tTaiKhoan> _tTaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTBDChanging(string value);
    partial void OnMaTBDChanged();
    partial void OnMaBDChanging(string value);
    partial void OnMaBDChanged();
    partial void OnMaTKChanging(string value);
    partial void OnMaTKChanged();
    partial void OnNgayCapChanging(System.DateTime value);
    partial void OnNgayCapChanged();
    partial void OnNgayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tTheBanDoc()
		{
			this._tGiaoDichMuonTras = new EntitySet<tGiaoDichMuonTra>(new Action<tGiaoDichMuonTra>(this.attach_tGiaoDichMuonTras), new Action<tGiaoDichMuonTra>(this.detach_tGiaoDichMuonTras));
			this._tBanDoc = default(EntityRef<tBanDoc>);
			this._tTaiKhoan = default(EntityRef<tTaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTBD", DbType="Char(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTBD
		{
			get
			{
				return this._MaTBD;
			}
			set
			{
				if ((this._MaTBD != value))
				{
					this.OnMaTBDChanging(value);
					this.SendPropertyChanging();
					this._MaTBD = value;
					this.SendPropertyChanged("MaTBD");
					this.OnMaTBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBD", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string MaBD
		{
			get
			{
				return this._MaBD;
			}
			set
			{
				if ((this._MaBD != value))
				{
					if (this._tBanDoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBDChanging(value);
					this.SendPropertyChanging();
					this._MaBD = value;
					this.SendPropertyChanged("MaBD");
					this.OnMaBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					if (this._tTaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="Date NOT NULL")]
		public System.DateTime NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTheBanDoc_tGiaoDichMuonTra", Storage="_tGiaoDichMuonTras", ThisKey="MaTBD", OtherKey="MaTBD")]
		public EntitySet<tGiaoDichMuonTra> tGiaoDichMuonTras
		{
			get
			{
				return this._tGiaoDichMuonTras;
			}
			set
			{
				this._tGiaoDichMuonTras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tBanDoc_tTheBanDoc", Storage="_tBanDoc", ThisKey="MaBD", OtherKey="MaBD", IsForeignKey=true)]
		public tBanDoc tBanDoc
		{
			get
			{
				return this._tBanDoc.Entity;
			}
			set
			{
				tBanDoc previousValue = this._tBanDoc.Entity;
				if (((previousValue != value) 
							|| (this._tBanDoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tBanDoc.Entity = null;
						previousValue.tTheBanDocs.Remove(this);
					}
					this._tBanDoc.Entity = value;
					if ((value != null))
					{
						value.tTheBanDocs.Add(this);
						this._MaBD = value.MaBD;
					}
					else
					{
						this._MaBD = default(string);
					}
					this.SendPropertyChanged("tBanDoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTaiKhoan_tTheBanDoc", Storage="_tTaiKhoan", ThisKey="MaTK", OtherKey="MaTK", IsForeignKey=true)]
		public tTaiKhoan tTaiKhoan
		{
			get
			{
				return this._tTaiKhoan.Entity;
			}
			set
			{
				tTaiKhoan previousValue = this._tTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._tTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tTaiKhoan.Entity = null;
						previousValue.tTheBanDocs.Remove(this);
					}
					this._tTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.tTheBanDocs.Add(this);
						this._MaTK = value.MaTK;
					}
					else
					{
						this._MaTK = default(string);
					}
					this.SendPropertyChanged("tTaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tGiaoDichMuonTras(tGiaoDichMuonTra entity)
		{
			this.SendPropertyChanging();
			entity.tTheBanDoc = this;
		}
		
		private void detach_tGiaoDichMuonTras(tGiaoDichMuonTra entity)
		{
			this.SendPropertyChanging();
			entity.tTheBanDoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tTheLoai")]
	public partial class tTheLoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThL;
		
		private string _TenThL;
		
		private EntitySet<tTaiLieu> _tTaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThLChanging(string value);
    partial void OnMaThLChanged();
    partial void OnTenThLChanging(string value);
    partial void OnTenThLChanged();
    #endregion
		
		public tTheLoai()
		{
			this._tTaiLieus = new EntitySet<tTaiLieu>(new Action<tTaiLieu>(this.attach_tTaiLieus), new Action<tTaiLieu>(this.detach_tTaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThL", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThL
		{
			get
			{
				return this._MaThL;
			}
			set
			{
				if ((this._MaThL != value))
				{
					this.OnMaThLChanging(value);
					this.SendPropertyChanging();
					this._MaThL = value;
					this.SendPropertyChanged("MaThL");
					this.OnMaThLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenThL
		{
			get
			{
				return this._TenThL;
			}
			set
			{
				if ((this._TenThL != value))
				{
					this.OnTenThLChanging(value);
					this.SendPropertyChanging();
					this._TenThL = value;
					this.SendPropertyChanged("TenThL");
					this.OnTenThLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tTheLoai_tTaiLieu", Storage="_tTaiLieus", ThisKey="MaThL", OtherKey="MaThL")]
		public EntitySet<tTaiLieu> tTaiLieus
		{
			get
			{
				return this._tTaiLieus;
			}
			set
			{
				this._tTaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tTaiLieus(tTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.tTheLoai = this;
		}
		
		private void detach_tTaiLieus(tTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.tTheLoai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tVaiTro")]
	public partial class tVaiTro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaVT;
		
		private string _TenVT;
		
		private EntitySet<tTaiKhoan> _tTaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVTChanging(string value);
    partial void OnMaVTChanged();
    partial void OnTenVTChanging(string value);
    partial void OnTenVTChanged();
    #endregion
		
		public tVaiTro()
		{
			this._tTaiKhoans = new EntitySet<tTaiKhoan>(new Action<tTaiKhoan>(this.attach_tTaiKhoans), new Action<tTaiKhoan>(this.detach_tTaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVT", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVT
		{
			get
			{
				return this._MaVT;
			}
			set
			{
				if ((this._MaVT != value))
				{
					this.OnMaVTChanging(value);
					this.SendPropertyChanging();
					this._MaVT = value;
					this.SendPropertyChanged("MaVT");
					this.OnMaVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenVT
		{
			get
			{
				return this._TenVT;
			}
			set
			{
				if ((this._TenVT != value))
				{
					this.OnTenVTChanging(value);
					this.SendPropertyChanging();
					this._TenVT = value;
					this.SendPropertyChanged("TenVT");
					this.OnTenVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tVaiTro_tTaiKhoan", Storage="_tTaiKhoans", ThisKey="MaVT", OtherKey="MaVT")]
		public EntitySet<tTaiKhoan> tTaiKhoans
		{
			get
			{
				return this._tTaiKhoans;
			}
			set
			{
				this._tTaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tTaiKhoans(tTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tVaiTro = this;
		}
		
		private void detach_tTaiKhoans(tTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tVaiTro = null;
		}
	}
}
#pragma warning restore 1591
